### ISSUE TITLE
Unable to install after last update

### ISSUE THREAD

**Issue by FatSquirrel93** [JasonLG1979/gnome-shell-extensions-mediaplayer#394]
Hey,

I´ve been using this extension for a while now, but I just updated today. 
After updating the extension, it wont show up anymore.

Inside Tweak Tool it is enabled, but pressing the configure icon next to it, has no effect.
extensions.gnome.org says it´s installed.

Other users are having the same issue (see comments https://extensions.gnome.org/extension/55/media-player-indicator/)

Is there any way, I can provide logs?

**Comment by treyssatvincent** [comment]
Same, uninstalled during upgrade. Now I can't install it.

My OS : Ubuntu 16.04 (on GNOME 3.18.2)

**Comment by JasonLG1979** [comment]
More than likely because of  https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/issues/393 It has since been fixed.

Can you test this release? https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/releases/tag/2.7.1

**Comment by treyssatvincent** [comment]
Fixed by 2.7.1 ! (Awesome work btw)

**Comment by bissybowo** [comment]
This issue remains the same to me. 
Ubuntu 16.04 (Gnome 3.18.5)

**Comment by JasonLG1979** [comment]
A new version has been uploaded to the extensions site. Just waiting for it to be approved.
