### ISSUE TITLE
Indicator does not refresh

### ISSUE THREAD

**Issue by pawel-jakubowski** [JasonLG1979/gnome-shell-extensions-mediaplayer#395]
Hi,

After latest update I have problems with non-refreshing indicator (always the same song is shown).
In journalctl I can see an error when change song with scroll event:
```
gnome-shell[2245]: JS ERROR: TypeError:  is null
                                           MPRISPlayer<._refreshProperties/</</<@/home/pjakubow/.local/share/gnome-shell/extensions/mediaplayer@patapon.info/player.js:795
                                           _proxyInvoker/asyncCallback@resource:///org/gnome/gjs/modules/overrides/Gio.js:86
````

**Comment by JasonLG1979** [comment]
That has been fixed.

Try this release. https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/releases/tag/2.7.2

A new version has been uploaded to the extension site it's awaiting approval.

**Comment by mart-w** [comment]
Version 2.7.2 does not seem to fix the problem for me – I also still get the same error message.

Just to make sure I’m not making a mistake here: Does it suffice to checkout the tagged commit and just re-run `./autogen.sh`, `make`, and `make install`?

**Comment by JasonLG1979** [comment]
> Just to make sure I’m not making a mistake here: Does it suffice to checkout the tagged commit and just re-run ./autogen.sh, make, and make install?

Just download the zip file in the release link and install the extension with GNOME Tweak Tool.

**Comment by JasonLG1979** [comment]
Apparently the version of GLib or at least the Gjs bindings doesn't catch the error properly when you try to call the "GetAll" props method on an interface that doesn't exist. The error should be passed to the async callback to be dealt with there but it's not. Deleting the entire call fixes the issue for me in Ubuntu 16.04 GNOME.

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/releases/tag/2.7.3

**Comment by mart-w** [comment]
That did indeed solve the problem. Thank you very much!
